/* Generated By:JavaCC: Do not edit this line. CircuitParserConstants.java */
package GCParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CircuitParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 4;
  /** RegularExpression Id. */
  int INPUT_MARK = 5;
  /** RegularExpression Id. */
  int OUTPUT_MARK = 6;
  /** RegularExpression Id. */
  int START_PARTY = 7;
  /** RegularExpression Id. */
  int END_PARTY = 8;
  /** RegularExpression Id. */
  int SIGNED_MARK = 9;
  /** RegularExpression Id. */
  int UNSIGNED_MARK = 10;
  /** RegularExpression Id. */
  int LINE_ENDING = 11;
  /** RegularExpression Id. */
  int INCLUDE = 12;
  /** RegularExpression Id. */
  int PATH = 13;
  /** RegularExpression Id. */
  int OPEN_PAREN = 14;
  /** RegularExpression Id. */
  int CLOSE_PAREN = 15;
  /** RegularExpression Id. */
  int COLON = 16;
  /** RegularExpression Id. */
  int COMMA = 17;
  /** RegularExpression Id. */
  int IDENTIFIER = 18;
  /** RegularExpression Id. */
  int INTEGER = 19;
  /** RegularExpression Id. */
  int DIGITS = 20;
  /** RegularExpression Id. */
  int LETTER = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<COMMENT>",
    "\".input\"",
    "\".output\"",
    "\".startparty\"",
    "\".endparty\"",
    "\"signed\"",
    "\"unsigned\"",
    "\"\\n\"",
    "\".include\"",
    "<PATH>",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\",\"",
    "<IDENTIFIER>",
    "<INTEGER>",
    "<DIGITS>",
    "<LETTER>",
  };

}
